'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var mongoose = require('mongoose');
var PlayerSchema = new mongoose.Schema({
  playerId: Number,
  ranking: Number,
  seasonId: Number,
  regionCode: String,
  firstName: String,
  lastName: String,
  teamName: String,
  playedPositions: String,
  age: Number,
  height: Number,
  weight: Number,
  positionText: String,
  apps: Number,
  subOn: Number,
  minsPlayed: Number,
  rating: Number,
  name: String,
  tackleWonTotal: Number,
  tackleTotalAttempted: Number,
  challengeLost: Number,
  interceptionAll: Number,
  foulGiven: Number,
  foulCommitted: Number,
  offsideGiven: Number,
  clearanceTotal: Number,
  dribbleLost: Number,
  dribbleWon: Number,
  outfielderBlock: Number,
  passCrossBlockedDefensive: Number,
  outfielderBlockedPass: Number,
  shotOffTarget: Number,
  shotOnPost: Number,
  shotOnTarget: Number,
  shotsTotal: Number,
  shotBlocked: Number,
  shotSixYardBox: Number,
  shotPenaltyArea: Number,
  shotOboxTotal: Number,
  shotOpenPlay: Number,
  shotCounter: Number,
  shotSetPiece: Number,
  penaltyTaken: Number,
  shotRightFoot: Number,
  shotLeftFoot: Number,
  shotHead: Number,
  goalSixYardBox: Number,
  goalPenaltyArea: Number,
  goalObox: Number,
  goalTotal: Number,
  goalOwn: Number,
  goalOpenPlay: Number,
  goalCounter: Number,
  goalSetPiece: Number,
  penaltyScored: Number,
  goalNormal: Number,
  goalRightFoot: Number,
  goalLeftFoot: Number,
  goalHead: Number,
  yellowCard: Number,
  redCard: Number,
  turnover: Number,
  dispossessed: Number,
  saveSixYardBox: Number,
  savePenaltyArea: Number,
  saveObox: Number,
  duelAerialWon: Number,
  duelAerialLost: Number,
  passLongBallAccurate: Number,
  passLongBallInaccurate: Number,
  shortPassAccurate: Number,
  shortPassInaccurate: Number,
  passCrossAccurate: Number,
  passCrossInaccurate: Number,
  passCornerAccurate: Number,
  passCornerInaccurate: Number,
  passFreekickAccurate: Number,
  passFreekickInaccurate: Number,
  keyPassLong: Number,
  keyPassShort: Number,
  keyPassCross: Number,
  keyPassCorner: Number,
  keyPassThroughball: Number,
  keyPassFreekick: Number,
  keyPassThrowin: Number,
  keyPassOther: Number,
  assistCross: Number,
  assistCorner: Number,
  assistThroughball: Number,
  assistFreekick: Number,
  assistThrowin: Number,
  assistOther: Number
});

module.exports = mongoose.model('Player', PlayerSchema);


