'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var mongoose = require('mongoose')
var PlayerSchema = new mongoose.Schema({
  id: Number,
  teamId: Number,
  playerId: Number,
  isCurrentPlayer: Boolean,
  gameStarted: Number,
  subOn: Number,
  subOff: Number,
  yellow: Number,
  secondYellow: Number,
  red: Number,
  goals: Number,
  assists: Number,
  totalPasses: Number,
  accuratePasses: Number,
  aerialWon: Number,
  aerialLost: Number,
  rating: Number,
  manOfTheMatch: Number,
  totalTackles: Number,
  interceptions: Number,
  fouls: Number,
  offsidesWon: Number,
  totalClearances: Number,
  wasDribbled: Number,
  totalShots: Number,
  shotsOnTarget: Number,
  shotsBlocked: Number,
  ownGoals: Number,
  keyPasses: Number,
  dribbles: Number,
  wasFouled: Number,
  offsides: Number,
  dispossesed: Number,
  turnovers: Number,
  totalCrosses: Number,
  accurateCrosses: Number,
  totalLongBalls: Number,
  accurateLongBalls: Number,
  totalThroughBalls: Number,
  accurateThroughBalls: Number,
  teamName: String,
  teamRegionCode: String,
  regionCode: String,
  positionText: String,
  playedPositionsRaw: String,
  height: Number,
  weight: Number,
  firstName: String,
  lastName: String,
  knownName: String,
  wSName: String,
  dateOfBirth: String,
  ranking: Number,
  positionShort: String,
  positionLong: String,
  name: String,
  age: Number
});

module.exports = mongoose.model('Player', PlayerSchema);


